# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='date completed')),
                ('category', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
    ]
